name: Screenshot
on:
  pull_request:
    branches:
      - main
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm ci
          cd src/assets/font
          wget -O fonts.zip https://drive.google.com/uc?export=download\&id=1sJCRhTucWoYCEY6XtXMGOUK-mBtOQEyB
          unzip -P ${{ secrets.FONT_PASSWORD }} fonts.zip
          npm run start & npx wait-on http://localhost:3000

      - name: Create screenshots
        uses: alexrogalskiy/github-action-screenshots@master
        with:
          url: 'http://localhost:3000'
          name: 'screenshot'
          path: 'screenshots'
          extension: 'png'
          encoding: 'binary'
          fullPage: true
          width: 1280
